name: Prettier
on:
    pull_request:
        paths:
            - '**/*.{js|json}'

jobs:
    format_check:
        name: Lint lesson files
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: tj-actions/changed-files@v41
            id: changed-files
            with:
              files: '**/*.{js|json}'
              separator: ' '
          - uses: creyD/prettier_action@v4.3
            with:
              dry: true
              prettier_options: --check ${{ steps.changed-files.outputs.all_changed_files }}