name: Prettier
on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.json'
      - '**/*.yml'

jobs:
  format_check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/prettier_action@v4.3
        with:
          dry: true
          only_changed: true
          prettier_options: --check .
