name: Prettier
on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.json'
      - '**/*.yml'

jobs:
  format_check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: True
          prettier_options: --check .
